[package]
name = "xcb"
version = "0.9.0"
authors = [ "Remi Thebault <remi.thebault@gmail.com>" ]
description = "Rust bindings and wrappers for XCB"
repository = "https://github.com/rtbo/rust-xcb"
documentation = "http://rtbo.github.io/rust-xcb/xcb/"
readme = "README.md"
keywords = ["xcb", "window", "xlib", "x11", "opengl"]
license = "MIT"
exclude = [ "examples/*", "scripts/*" ]
build = "build/main.rs"
autoexamples = false

[build-dependencies]
libc = "0.2"
quick-xml = "0.22.0"

[dependencies]
libc = "0.2"
log = "0.4"

[dependencies.x11]
version = "2.3"
optional = true
features = ["xlib"]

[features]
xlib_xcb = ["x11/xlib"]
thread = []

composite = [ "xfixes" ]
damage = [ "xfixes" ]
dpms = []
dri2 = []
dri3 = []
genericevent = []
glx = []
present = [ "render", "xfixes", "sync" ]
randr = [ "render" ]
record = []
render = []
res = []
screensaver = []
shape = []
shm = []
sync = []
xevie = []
xf86dri = []
xf86vidmode = []
xfixes = [ "render", "shape" ]
xinerama = []
input = [ "xfixes" ]
xkb = []
x_print = []
selinux = []
test = []
xvmc = [ "xv" ]
xv = [ "shm" ]

# ge and xf86vidmode are apparently nor built neither installed by libxcb C project
# extension xinput is broken
# all others are in debug_all whose purpose is to check build of extensions
debug_all = [ "thread", "composite", "damage", "dpms", "dri2", "dri3",
        "glx", "randr", "record", "render", "res", "screensaver", "shape",
        "shm", "xevie", "xf86dri", "xfixes", "xinerama", "xkb",
        "x_print", "selinux", "test", "xvmc", "xv", "xlib_xcb" ]

[dev-dependencies]
gl = "0.5.2"

[dev-dependencies.x11]
version = "2.3"
features = ["xlib", "glx"]

[[example]]
name = "basic_window"

[[example]]
name = "connect_str"

[[example]]
name = "connect"

[[example]]
name = "draw_root_window"

[[example]]
name = "drawing"

[[example]]
name = "opengl_window"
required-features = ["xlib_xcb", "dri2"]

[[example]]
name = "randr_crtc_info"
required-features = ["randr"]

[[example]]
name = "ffi_randr_crtc_info"
required-features = ["randr"]

[[example]]
name = "randr_crtc_listen"
required-features = ["randr"]

[[example]]
name = "randr_screen_info"
required-features = ["randr"]

[[example]]
name = "randr_screen_modes"
required-features = ["randr"]

[[example]]
name = "screen_info"

[[example]]
name = "ffi_screen_info"

[[example]]
name = "threaded_window"
required-features = ["thread"]

[[example]]
name = "xkb_init"
required-features = ["xkb"]

[[example]]
name = "ffi_xkb_init"
required-features = ["xkb"]
