[package]

name = "xcb"
version = "0.3.0"
authors = [ "Aatch" ]
build = "build.rs"

[lib]
name = "xcb"
path = "src/xcb.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
libc = "0.2"


# cargo does not seam to support example.features yet.
# That is addressed in cargo/#1570
#[[example]]
#name = "randr_crtc_info"
#features = "randr"


[features]
bigreq = []
composite = [ "xfixes" ]
damage = [ "xfixes" ]
dpms = []
dri2 = []
dri3 = []
ge = []
glx = []
present = [ "render", "xfixes", "sync" ]
randr = [ "render" ]
record = []
render = []
res = []
screensaver = []
shape = []
shm = []
sync = []
xc_misc = []
xevie = []
xf86dri = []
xf86vidmode = []
xfixes = [ "render", "shape" ]
xinerama = []
xinput = [ "xfixes" ]
xkb = []
xprint = []
xselinux = []
xtest = []
xvmc = [ "xv" ]
xv = [ "shm" ]

# ge and xf86vidmode are apparently nor built neither installed by libxcb C project
# extensions xkb and xinput are broken because of switches
# all others are in debug_all whose purpose is to enable all extensions to check build
debug_all = [ "bigreq", "composite", "damage", "dpms", "dri2", "dri3", "glx", "randr", "record", "render", "res", "screensaver", "shape", "shm", "xc_misc", "xevie", "xf86dri", "xfixes", "xinerama", "xprint", "xselinux", "xtest", "xvmc", "xv" ]
