on:
  push:
    branches:
      - '*'
      - '!main'

name: Build Branch documentation

jobs:
  build:
    name: Build Branch documentation and deploy to gh-pages
    runs-on: ubuntu-latest
    env:
      RXCB_RUSTFMT: 1
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libgl1-mesa-dev \
            libxcb-composite0-dev \
            libxcb-damage0-dev \
            libxcb-dpms0-dev \
            libxcb-dri2-0-dev \
            libxcb-dri3-dev \
            libxcb-glx0-dev \
            libxcb-present-dev \
            libxcb-randr0-dev \
            libxcb-record0-dev \
            libxcb-render0-dev \
            libxcb-res0-dev \
            libxcb-screensaver0-dev \
            libxcb-shape0-dev \
            libxcb-shm0-dev \
            libxcb-sync-dev \
            libxcb-xf86dri0-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxcb-xtest0-dev \
            libxcb-xv0-dev \
            libxcb-xvmc0-dev \
            libx11-xcb-dev

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Push on gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: target/doc
          target-folder: branches/${{ steps.branch-name.outputs.current_branch }}
